### ISSUE TITLE
Замена клумб во дворе

### ISSUE THREAD

**Issue by HelenaGV** [grishina16/issues#12]

**Comment by HelenaGV** [comment]
![image](https://user-images.githubusercontent.com/94982789/153557536-7fbd96d5-c2ad-4ea0-883a-23a2ac7d5ed2.jpeg)

**Comment by maxim-kuvyrkov** [comment]
Дупликат https://github.com/grishina16/issues/issues/3 ?

**Comment by HelenaGV** [comment]
Ой точно, удалю

**Comment by HelenaGV** [comment]
А как удалять? Не пойму

**Comment by maxim-kuvyrkov** [comment]
> А как удалять? Не пойму

Я закрыл как дубликат.
